Update queries.md, removed firstOrFail docs because not available on query builder
when calling firstOrFail on DB facade query builder, it throws exception

local.ERROR: Call to undefined method Illuminate\Database\Query\Builder::firstOrFail() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Query\\Builder::firstOrFail() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(4390): Illuminate\\Database\\Query\\Builder::throwBadMethodCallException('firstOrFail')
#1 /var/www/html/database/migrations/2024

function should not be in docs until readily available to use

https://stackoverflow.com/questions/79145864/call-to-undefined-method-illuminate-database-query-builderfirstorfail-lara?noredirect=1#comment139562863_79145864